# Generated by Django 2.2.4 on 2019-08-03 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rainforest', '0003_auto_20190803_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product_id',
            new_name='product',
        ),
    ]
